import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { apiKey, examName, generationType, difficulty, subject, numQuestions } = body;

    if (!apiKey) {
      return NextResponse.json({ error: "OpenRouter API Key is required" }, { status: 400 });
    }

    const questionCount = numQuestions || 5;

    const payload = {
      model: "openrouter/free",
      messages: [
        {
          role: "system",
          content: `You are an expert academic test creator. Create high-quality, challenging questions based strictly on the user's exact requirements. Your response MUST be valid JSON containing an array of EXACTLY ${questionCount} objects. Each object should represent a query with the following fields: {"question": "string", "options": ["string", "string", "string", "string"], "correctAnswer": "string"}. CRITICAL REQUIREMENT: You MUST provide EXACTLY 4 options in the "options" array for every single question. Never 3, never 5. Important: If you use LaTeX or math notation, you MUST double-escape your backslashes to ensure valid JSON (e.g. use \\\\( and \\\\) instead of \\( and \\)). Do not use any markdown formatting or any text outside the JSON array. Make absolutely certain you generate exactly ${questionCount} items.`
        },
        {
          role: "user",
          content: `Create EXACTLY ${questionCount} questions with these parameters:\n- Target Exam: ${examName}\n- Generation Goal: ${generationType}\n- Subject/Topic Area: ${subject || 'General'}\n- Difficulty Level: ${difficulty}\n\nIMPORTANT: It is critical that your JSON array length is exactly ${questionCount} to simulate a ${generationType}.`
        }
      ]
    };

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorText = await response.text();
      return NextResponse.json({ error: `OpenRouter API error: ${errorText}` }, { status: response.status });
    }

    const data = await response.json();
    let content = data.choices?.[0]?.message?.content || "[]";
    
    content = content.trim();
    if(content.startsWith("```json")) {
        content = content.replace(/^```json\n?/, "").replace(/\n?```$/, "");
    }
    if(content.startsWith("```")) {
        content = content.replace(/^```\n?/, "").replace(/\n?```$/, "");
    }

    // Fix unescaped backslashes typically generated by LaTeX responses. 
    // This finds unescaped backslashes not followed by valid JSON control chars and double escapes them.
    content = content.replace(/\\([^"\\/bfnrtu])/g, '\\\\$1');

    let questions: any[] = [];
    try {
      questions = JSON.parse(content);
      
      // Fallback normalizer: guarantee exactly 4 options so the UI never breaks
      questions = questions.map(q => {
        if (!Array.isArray(q.options)) q.options = ["Option A", "Option B", "Option C", "Option D"];
        while (q.options.length < 4) {
          q.options.push("None of the above");
        }
        if (q.options.length > 4) {
          q.options = q.options.slice(0, 4);
          if (!q.options.includes(q.correctAnswer)) {
             q.correctAnswer = q.options[0]; // fallback safely
          }
        }
        return q;
      });

    } catch {
       return NextResponse.json({ error: "Failed to parse JSON from AI model. Content returned: " + content }, { status: 500 });
    }

    return NextResponse.json({ questions });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
